In [1]:
import pandas as pd
import numpy as np
import yfinance as yf

ewz = yf.download("EWZ", start="2010-01-01", end="2026-03-31", interval="1d")

[*********************100%***********************]  1 of 1 completed

In [2]:
ewz.head()

Price           Close       High        Low       Open    Volume
Ticker            EWZ        EWZ        EWZ        EWZ       EWZ
Date
2010-01-04  38.441902  38.556444  37.849261  37.968784  12115900
2010-01-05  38.486713  38.800466  38.167983  38.546477  12605000
2010-01-06  38.740711  38.989720  38.317398  38.431940  11989600
2010-01-07  38.312412  38.566402  38.098265  38.496680   9750900
2010-01-08  38.581341  38.825368  38.347272  38.541499   9772600

In [3]:
ewz.tail()

Price           Close       High        Low       Open    Volume
Ticker            EWZ        EWZ        EWZ        EWZ       EWZ
Date
2026-03-24  36.669998  36.849998  36.110001  36.160000  34959900
2026-03-25  37.540001  37.799999  37.200001  37.349998  33715900
2026-03-26  36.799999  37.439999  36.750000  37.139999  27560600
2026-03-27  36.630001  37.139999  36.459999  36.490002  27150400
2026-03-30  36.770000  37.250000  36.500000  37.000000  21224600

In [4]:
ewz.to_csv("/Users/anirudh/Documents/WQU/Course 02 600 FINMANCIAL DATA/GWP/EWZ.csv")